### ISSUE TITLE
Comment 2

### ISSUE THREAD

**Issue by SalimovAzimjon** [naimovfayyoz/Shop#2]
https://github.com/naimovfayyoz/Shop/blob/7144133e8f2d90f2f58ceb9d59c1ff678a58d36f/app/src/main/java/uz/fayyoz/a1shop/data/repository/signUp/SignUpRepoImpl.kt#L13

suspend functions in any class should be safe for calling from main thread. Meaning you should change coroutine context and dispatchers in repository here, although retrofit already switches to IO dispatcher underhood it is better to switch repository yourself as there might be another logic

**Comment by naimovfayyoz** [comment]
Fixed( in flow return type classes has been implemented flowOn(Dispatchers.IO) in other cases withContext(Dispatchers.IO))
